-- Migration: 0001_initial_schema
-- Generated by Drizzle Kit — do not edit manually

CREATE TYPE job_state AS ENUM (
  'CREATED', 'QUEUED', 'STARTED', 'PROVIDER_RUNNING',
  'UPLOADING', 'SUCCEEDED', 'FAILED', 'CANCELLED'
);

CREATE TYPE provider_name AS ENUM ('veo', 'kling', 'anthropic', 'vllm', 'gemini');
CREATE TYPE job_type AS ENUM ('TEXT_TO_VIDEO', 'IMAGE_TO_VIDEO', 'TEXT_TO_TEXT');
CREATE TYPE project_status AS ENUM ('ACTIVE', 'ARCHIVED');
CREATE TYPE asset_status AS ENUM ('PENDING', 'CONFIRMED', 'FAILED');
CREATE TYPE export_status AS ENUM ('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED');
CREATE TYPE export_format AS ENUM ('MP4', 'MOV', 'WEBM');
CREATE TYPE export_resolution AS ENUM ('1080p', '4K', '720p');
CREATE TYPE audit_action AS ENUM (
  'USER_LOGIN', 'USER_LOGOUT',
  'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED',
  'ASSET_UPLOADED', 'ASSET_CONFIRMED',
  'JOB_CREATED', 'JOB_STATE_CHANGED', 'JOB_CANCELLED',
  'VERSION_CREATED', 'EXPORT_CREATED', 'EXPORT_COMPLETED',
  'CONTROL_SNAPSHOT_READ'
);

CREATE TABLE users (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       VARCHAR(320) NOT NULL,
  name        VARCHAR(255) NOT NULL,
  password_hash TEXT NOT NULL,
  role        VARCHAR(50) NOT NULL DEFAULT 'user',
  email_verified BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX users_email_idx ON users (email);

CREATE TABLE projects (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name        VARCHAR(255) NOT NULL,
  description TEXT,
  status      project_status NOT NULL DEFAULT 'ACTIVE',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX projects_user_id_idx ON projects (user_id);
CREATE INDEX projects_status_idx ON projects (status);

CREATE TABLE assets (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES users(id),
  filename     VARCHAR(512) NOT NULL,
  content_type VARCHAR(255) NOT NULL,
  size_bytes   BIGINT,
  storage_key  TEXT NOT NULL,
  public_url   TEXT,
  status       asset_status NOT NULL DEFAULT 'PENDING',
  metadata     JSONB NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX assets_project_id_idx ON assets (project_id);
CREATE INDEX assets_user_id_idx ON assets (user_id);
CREATE UNIQUE INDEX assets_storage_key_idx ON assets (storage_key);

CREATE TABLE prompts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES users(id),
  text        TEXT NOT NULL,
  version     INTEGER NOT NULL DEFAULT 1,
  metadata    JSONB NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX prompts_project_id_idx ON prompts (project_id);
CREATE INDEX prompts_version_idx ON prompts (project_id, version);

CREATE TABLE jobs (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id            UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id               UUID NOT NULL REFERENCES users(id),
  prompt_id             UUID NOT NULL REFERENCES prompts(id),
  provider              provider_name NOT NULL,
  job_type              job_type NOT NULL,
  state                 job_state NOT NULL DEFAULT 'CREATED',
  input_asset_id        UUID REFERENCES assets(id),
  output_asset_id       UUID REFERENCES assets(id),
  provider_operation_id TEXT,
  params                JSONB NOT NULL DEFAULT '{}',
  idempotency_key       VARCHAR(255) NOT NULL,
  attempt_count         INTEGER NOT NULL DEFAULT 0,
  max_attempts          INTEGER NOT NULL DEFAULT 3,
  error_code            VARCHAR(100),
  error_message         TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at            TIMESTAMPTZ,
  completed_at          TIMESTAMPTZ
);
CREATE INDEX jobs_project_id_idx ON jobs (project_id);
CREATE INDEX jobs_user_id_idx ON jobs (user_id);
CREATE INDEX jobs_state_idx ON jobs (state);
CREATE UNIQUE INDEX jobs_idempotency_key_idx ON jobs (idempotency_key);
CREATE INDEX jobs_created_at_idx ON jobs (created_at);

CREATE TABLE versions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id     UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  job_id         UUID NOT NULL REFERENCES jobs(id),
  asset_id       UUID NOT NULL REFERENCES assets(id),
  version_number INTEGER NOT NULL,
  label          VARCHAR(255),
  metadata       JSONB NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX versions_project_id_idx ON versions (project_id);
CREATE UNIQUE INDEX versions_project_version_idx ON versions (project_id, version_number);

CREATE TABLE exports (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id          UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id             UUID NOT NULL REFERENCES users(id),
  version_ids         JSONB NOT NULL,
  format              export_format NOT NULL,
  resolution          export_resolution NOT NULL,
  fps                 INTEGER NOT NULL,
  status              export_status NOT NULL DEFAULT 'PENDING',
  output_url          TEXT,
  output_storage_key  TEXT,
  error_message       TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at        TIMESTAMPTZ
);
CREATE INDEX exports_project_id_idx ON exports (project_id);
CREATE INDEX exports_user_id_idx ON exports (user_id);
CREATE INDEX exports_status_idx ON exports (status);

CREATE TABLE audit_events (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID REFERENCES users(id) ON DELETE SET NULL,
  action        audit_action NOT NULL,
  resource_type VARCHAR(100) NOT NULL,
  resource_id   UUID,
  meta          JSONB NOT NULL DEFAULT '{}',
  ip_address    VARCHAR(45),
  user_agent    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX audit_events_user_id_idx ON audit_events (user_id);
CREATE INDEX audit_events_action_idx ON audit_events (action);
CREATE INDEX audit_events_resource_idx ON audit_events (resource_type, resource_id);
CREATE INDEX audit_events_created_at_idx ON audit_events (created_at);

CREATE TABLE control_snapshots (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_id          VARCHAR(255) NOT NULL,
  computed_at          TIMESTAMPTZ NOT NULL,
  system_health_score  INTEGER NOT NULL,
  provider_health      JSONB NOT NULL DEFAULT '[]',
  job_queue_stats      JSONB NOT NULL DEFAULT '{}',
  active_job_count     INTEGER NOT NULL DEFAULT 0,
  metrics              JSONB NOT NULL DEFAULT '[]',
  alerts               JSONB NOT NULL DEFAULT '[]',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX control_snapshots_snapshot_id_idx ON control_snapshots (snapshot_id);
CREATE INDEX control_snapshots_computed_at_idx ON control_snapshots (computed_at);
