import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MagneticButton } from "../components/fx/MagneticButton";
import { TiltCard } from "../components/fx/TiltCard";
import { BorderBeam } from "../components/fx/BorderBeam";
import { CursorGlow } from "../components/fx/CursorGlow";
import { Marquee } from "../components/fx/Marquee";
import { AuroraConductor } from "../components/fx/AuroraConductor";
import { CommandPalette } from "../components/ui/CommandPalette";
import { useThemeStore } from "../lib/store/theme";
import { useState } from "react";
import { Sparkles, Code2, Zap, Shield, Palette, Clock } from "lucide-react";
export default function Landing() {
    const { theme, setTheme } = useThemeStore();
    const [hoveredCard, setHoveredCard] = useState(null);
    const features = [
        { id: "instant", icon: Zap, title: "Instant Generation", desc: "AI-powered HTML generation in real-time" },
        { id: "sandbox", icon: Shield, title: "Sandboxed Preview", desc: "Safe iframe execution with script-only permissions" },
        { id: "themes", icon: Palette, title: "4 Stunning Themes", desc: "Aurora, Daybreak, Synthwave, Terminal" },
        { id: "history", icon: Clock, title: "History Tracking", desc: "Append-only snapshot system with fork support" },
        { id: "monaco", icon: Code2, title: "Monaco Editor", desc: "Full-featured code editing with syntax highlighting" },
        { id: "motion", icon: Sparkles, title: "Motion Design", desc: "Smooth animations powered by Motion" },
    ];
    return (_jsxs("div", { className: "min-h-screen bg-[var(--bg)] text-[var(--ink)] overflow-hidden", children: [_jsx(CursorGlow, {}), _jsx(CommandPalette, {}), _jsxs("div", { className: "relative z-10", children: [_jsxs("nav", { className: "flex items-center justify-between px-8 py-6", children: [_jsxs("div", { className: "flex items-center gap-2 text-xl font-bold", children: [_jsx(Sparkles, { className: "h-6 w-6 text-[var(--accent)]" }), _jsx("span", { children: "VibeForge" })] }), _jsx("div", { className: "flex items-center gap-4", children: _jsxs("select", { value: theme, onChange: (e) => setTheme(e.target.value), className: "rounded-lg bg-[var(--surface)] px-3 py-2 text-sm border border-[var(--line)] text-[var(--ink)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]", children: [_jsx("option", { value: "aurora", children: "Aurora" }), _jsx("option", { value: "daybreak", children: "Daybreak" }), _jsx("option", { value: "synthwave", children: "Synthwave" }), _jsx("option", { value: "terminal", children: "Terminal" })] }) })] }), _jsxs("section", { className: "relative px-8 py-32", children: [_jsx(AuroraConductor, { className: "absolute inset-0 opacity-30" }), _jsxs("div", { className: "relative z-10 max-w-4xl mx-auto text-center", children: [_jsxs("h1", { className: "text-7xl font-bold mb-6 leading-tight", children: ["Turn vibe into code.", _jsx("br", {}), _jsx("span", { className: "text-[var(--accent)]", children: "Instantly." })] }), _jsx("p", { className: "text-xl text-[var(--muted)] mb-12 max-w-2xl mx-auto", children: "Generate production-ready HTML from natural language prompts. Powered by Claude, sandboxed for safety, designed for speed." }), _jsxs("div", { className: "flex items-center justify-center gap-4", children: [_jsx(MagneticButton, { onClick: () => window.location.pathname = "/studio", children: "Open the Studio" }), _jsx("button", { onClick: () => document.getElementById("demo")?.scrollIntoView({ behavior: "smooth" }), className: "rounded-[10px] border-2 border-[var(--line)] px-6 py-3 font-medium text-[var(--ink)] hover:border-[var(--accent)] transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--accent)]", children: "Watch a vibe" })] })] })] }), _jsx("section", { className: "px-8 py-16", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsx("h2", { className: "text-3xl font-bold mb-8 text-center", children: "Prompt Examples" }), _jsx(Marquee, {})] }) }), _jsx("section", { className: "px-8 py-16", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsx("h2", { className: "text-3xl font-bold mb-12 text-center", children: "Features" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: features.map((feature) => {
                                        const Icon = feature.icon;
                                        return (_jsxs(TiltCard, { className: "relative p-6 rounded-[20px] bg-[var(--surface)] border border-[var(--line)]", onMouseEnter: () => setHoveredCard(feature.id), onMouseLeave: () => setHoveredCard(null), children: [_jsx(BorderBeam, { active: hoveredCard === feature.id }), _jsx(Icon, { className: "h-8 w-8 text-[var(--accent)] mb-4" }), _jsx("h3", { className: "text-xl font-bold mb-2", children: feature.title }), _jsx("p", { className: "text-[var(--muted)]", children: feature.desc })] }, feature.id));
                                    }) })] }) }), _jsx("section", { id: "demo", className: "px-8 py-16", children: _jsxs("div", { className: "max-w-4xl mx-auto text-center", children: [_jsx("h2", { className: "text-3xl font-bold mb-6", children: "Proof Strip" }), _jsx("div", { className: "rounded-[20px] bg-[var(--surface)] border border-[var(--line)] p-8", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-[var(--line)]", children: [_jsx("th", { className: "pb-3 font-medium text-[var(--muted)]", children: "Gate" }), _jsx("th", { className: "pb-3 font-medium text-[var(--muted)]", children: "Status" })] }) }), _jsxs("tbody", { className: "text-[var(--ink)]", children: [_jsxs("tr", { className: "border-b border-[var(--line)]", children: [_jsx("td", { className: "py-3", children: "Typecheck" }), _jsx("td", { className: "py-3", children: "\u2713 pnpm typecheck" })] }), _jsxs("tr", { className: "border-b border-[var(--line)]", children: [_jsx("td", { className: "py-3", children: "Lint" }), _jsx("td", { className: "py-3", children: "\u2713 pnpm lint" })] }), _jsxs("tr", { className: "border-b border-[var(--line)]", children: [_jsx("td", { className: "py-3", children: "Test" }), _jsx("td", { className: "py-3", children: "\u2713 pnpm test (\u226525 tests, \u226580% coverage)" })] }), _jsxs("tr", { className: "border-b border-[var(--line)]", children: [_jsx("td", { className: "py-3", children: "Build" }), _jsx("td", { className: "py-3", children: "\u2713 pnpm build" })] }), _jsxs("tr", { children: [_jsx("td", { className: "py-3", children: "Secret Scan" }), _jsx("td", { className: "py-3", children: "\u2713 No secrets in bundle" })] })] })] }) })] }) }), _jsx("footer", { className: "px-8 py-12 border-t border-[var(--line)]", children: _jsxs("div", { className: "max-w-6xl mx-auto flex items-center justify-between", children: [_jsx("p", { className: "text-[var(--muted)] text-sm", children: "VibeForge Studio \u00B7 Fail-closed by design \u00B7 No proof, no PASS" }), _jsxs("div", { className: "flex items-center gap-6 text-sm text-[var(--muted)]", children: [_jsx("button", { onClick: () => setTheme("aurora"), className: "hover:text-[var(--accent)]", children: "Aurora" }), _jsx("button", { onClick: () => setTheme("daybreak"), className: "hover:text-[var(--accent)]", children: "Daybreak" }), _jsx("button", { onClick: () => setTheme("synthwave"), className: "hover:text-[var(--accent)]", children: "Synthwave" }), _jsx("button", { onClick: () => setTheme("terminal"), className: "hover:text-[var(--accent)]", children: "Terminal" })] })] }) })] })] }));
}
