/**
 * Cache-aware Input Tokens Per Minute (ITPM) calculation.
 *
 * Anthropic rate-limit accounting for input tokens:
 *   - Standard models: only `input_tokens` counts toward the ITPM limit.
 *     `cache_read_input_tokens` is excluded.
 *   - † models: `input_tokens + cache_read_input_tokens` both count toward
 *     the ITPM limit, so cache reads are included in throttle decisions.
 *
 * The † set is derived from Anthropic's pricing page where cache-read tokens
 * are billed at the same rate-limit tier as regular input tokens.
 */

// ---------------------------------------------------------------------------
// † (dagger) model registry
// ---------------------------------------------------------------------------

/**
 * Model IDs where cache_read_input_tokens counts toward the ITPM limit.
 * Match on prefix so point-releases (e.g. -20241022) are captured automatically.
 *
 * Sources: Anthropic pricing page (checked 2026-04-30).
 *   claude-3-haiku:        cache reads count toward input TPM
 *   claude-3-5-haiku:      cache reads count toward input TPM
 */
const DAGGER_MODEL_PREFIXES: readonly string[] = [
  'claude-3-haiku',
  'claude-3-5-haiku',
] as const;

/**
 * Returns `true` when the model is a "†" model whose cache-read tokens count
 * toward the ITPM rate-limit.
 */
export const isDaggerModel = (modelId: string): boolean =>
  DAGGER_MODEL_PREFIXES.some((prefix) => modelId.startsWith(prefix));

// ---------------------------------------------------------------------------
// Usage shape (subset of Anthropic's usage object)
// ---------------------------------------------------------------------------

export interface TokenUsage {
  /** Tokens generated by the model that were not retrieved from the cache. */
  readonly input_tokens: number;
  /**
   * Tokens retrieved from the prompt cache.  `undefined` when the model does
   * not support prompt caching or the field was not returned by the API.
   */
  readonly cache_read_input_tokens?: number;
  /** Created cache tokens (not counted toward ITPM in either mode). */
  readonly cache_creation_input_tokens?: number;
  /** Output tokens (not counted toward ITPM). */
  readonly output_tokens?: number;
}

// ---------------------------------------------------------------------------
// ITPM calculation
// ---------------------------------------------------------------------------

/**
 * Calculate the effective Input Tokens Per Minute (ITPM) cost for a single
 * response, respecting the cache-aware mode for the given model.
 *
 * @param modelId  - The Anthropic model ID used for the request.
 * @param usage    - Token usage returned by the Anthropic API.
 * @returns        Effective input token count that counts toward the ITPM limit.
 */
export const effectiveItpm = (modelId: string, usage: TokenUsage): number => {
  const base = usage.input_tokens;
  if (isDaggerModel(modelId)) {
    return base + (usage.cache_read_input_tokens ?? 0);
  }
  return base;
};

/**
 * Determine whether the cumulative ITPM would exceed `limitItpm` if a new
 * request with `estimatedInputTokens` is added.
 *
 * @param modelId              - Model being targeted.
 * @param limitItpm            - The `anthropic-ratelimit-input-tokens-limit` value.
 * @param remainingItpm        - The `anthropic-ratelimit-input-tokens-remaining` value.
 * @param estimatedInputTokens - Projected input tokens for the next request.
 * @param estimatedCacheRead   - Projected cache-read tokens (optional; only
 *                               meaningful for † models).
 * @returns `true` when the request would be safe to send without hitting the limit.
 */
export const wouldFitItpm = (
  modelId: string,
  limitItpm: number,
  remainingItpm: number,
  estimatedInputTokens: number,
  estimatedCacheRead = 0,
): boolean => {
  const cost = isDaggerModel(modelId)
    ? estimatedInputTokens + estimatedCacheRead
    : estimatedInputTokens;
  return cost <= remainingItpm && remainingItpm <= limitItpm;
};
